### ISSUE TITLE
Linux建议

### ISSUE THREAD

**Issue by fanTMT** [xuan06zyx/blive-vod#2]
╰─λ python main.py
报错
Traceback (most recent call last):
File "/home/fan/Downloads/blive-vod/main.py", line 12, in <module>
import blivedm.models.web as web_models
ModuleNotFoundError: No module named 'blivedm.models.web'; 'blivedm.models' is not a package

**Comment by xuan06zyx** [comment]
检查是否有blivedm文件夹，如有则不清楚原因，可能是python版本问题，我用的3.10，Linux到底是否能运行我无法保证，该项目创立之初只考虑了Windows，不过目前找到了更好的（可能）api，如果有缘我可能会小幅度重构一次项目，如果有思路可以提交pr

**Comment by fanTMT** [comment]
[Releases v2.01] 缺少blivedm文件夹 
git 源码 缺少 config.py 取releases的config.py文件就可以运行
